language:
  ruby

rvm:
  - 1.9
  - 2.0
  - 2.1
  - 2.2
  - ruby-head

env:
  matrix:
    - "NARRAY=1"
    - ""

matrix:
  allow_failures:
    - rvm: ruby-head

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libgsl0-dev
