language:
  ruby

rvm:
  - 1.9
  - 2.0
  - 2.1
  - 2.2
  - 2.3.0
  - ruby-head
  - rbx-2

env:
  matrix:
    - "NARRAY=1"
    - "NMATRIX=1"
    - ""

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: rbx-2

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libgsl0-dev
  - bundle exec bundle install
